name: restapi
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

environment:
  sdk: '>=2.18.0 <3.0.0'

flutter:
  uses-material-design: true